package com.askolds.homeinventory.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3E6A00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA7F944)
val md_theme_light_onPrimaryContainer = Color(0xFF0F2000)
val md_theme_light_secondary = Color(0xFF006A64)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF71F7EC)
val md_theme_light_onSecondaryContainer = Color(0xFF00201E)
val md_theme_light_tertiary = Color(0xFF00639C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCEE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D33)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCF5)
val md_theme_light_onBackground = Color(0xFF1B1C18)
val md_theme_light_surface = Color(0xFFFDFCF5)
val md_theme_light_onSurface = Color(0xFF1B1C18)
val md_theme_light_surfaceVariant = Color(0xFFE1E4D5)
val md_theme_light_onSurfaceVariant = Color(0xFF44483D)
val md_theme_light_outline = Color(0xFF75796C)
val md_theme_light_inverseOnSurface = Color(0xFFF2F1E9)
val md_theme_light_inverseSurface = Color(0xFF30312C)
val md_theme_light_inversePrimary = Color(0xFF8CDC25)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF3E6A00)
val md_theme_light_outlineVariant = Color(0xFFC5C8BA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF8CDC25)
val md_theme_dark_onPrimary = Color(0xFF1E3700)
val md_theme_dark_primaryContainer = Color(0xFF2E4F00)
val md_theme_dark_onPrimaryContainer = Color(0xFFA7F944)
val md_theme_dark_secondary = Color(0xFF50DBD0)
val md_theme_dark_onSecondary = Color(0xFF003734)
val md_theme_dark_secondaryContainer = Color(0xFF00504B)
val md_theme_dark_onSecondaryContainer = Color(0xFF71F7EC)
val md_theme_dark_tertiary = Color(0xFF98CBFF)
val md_theme_dark_onTertiary = Color(0xFF003354)
val md_theme_dark_tertiaryContainer = Color(0xFF004A77)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEE5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DB)
val md_theme_dark_surface = Color(0xFF1B1C18)
val md_theme_dark_onSurface = Color(0xFFE3E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF44483D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C8BA)
val md_theme_dark_outline = Color(0xFF8E9285)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C18)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DB)
val md_theme_dark_inversePrimary = Color(0xFF3E6A00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF8CDC25)
val md_theme_dark_outlineVariant = Color(0xFF44483D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA3F540)

// Success colors
val Success = Color(0xFF66BB6A)
val light_Success = Color(0xFF83DA85)
val light_onSuccess = Color(0xFF00390E)
val light_SuccessContainer = Color(0xFF005318)
val light_onSuccessContainer = Color(0xFF9FF79F)
val dark_Success = Color(0xFF126D27)
val dark_onSuccess = Color(0xFFFFFFFF)
val dark_SuccessContainer = Color(0xFF9FF79F)
val dark_onSuccessContainer = Color(0xFF002105)
//