name: Generate and Submit dependency graph
on:
  push:
    branches:
    -   main
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout the code
            uses: actions/checkout@v4

        -   name: Setup JAVA 17
            uses: actions/setup-java@v3
            with:
                distribution: 'corretto'
                java-version: 17

        -   name: Setup Gradle to generate and submit dependency graphs
            uses: gradle/gradle-build-action@v2
            with:
                dependency-graph: generate-and-submit
        
        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew

        -   name: Run a build and generate the dependency graph which will be submitted post-job
            run: ./gradlew build